[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust - Core"
documentation = "https://docs.rs/rusoto_core"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_core"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.40.0"
homepage = "https://www.rusoto.org/"
exclude = ["test_resources/*"]
edition = "2018"

[badges]
appveyor = { repository = "rusoto/rusoto", branch = "master" }
azure-devops = { project = "matthewkmayer/Rusoto", pipeline = "rusoto.rusoto", build="1" }

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
bytes = "0.4.12"
futures-preview = { version = "0.3.0-alpha.18", features = ["async-await", "nightly"] }
hmac = "0.5.0"
http = "0.1.17"
hyper = { git = "https://github.com/hyperium/hyper.git", branch = "master" }
hyper-rustls = { git = "https://github.com/dbcfd/hyper-rustls.git", branch = "futures", optional = true }
hyper-tls = { git = "https://github.com/dbcfd/hyper-tls.git", branch = "tokio-alpha4", optional = true }
lazy_static = "1.0"
log = "0.4.1"
md5 = "0.3.6"
pin-project = "0.4.0-alpha.11"
base64 = "0.9"
hex = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.2"
sha2 = "0.7.0"
time = "0.1.35"
url = "1.6.0"
tokio = "0.2.0-alpha.4"
xml-rs = "0.7"

[dependencies.rusoto_credential]
path = "../credential"
version = "0.40"

[dependencies.clippy]
optional = true
version = "0.0"

[dev-dependencies]
env_logger = "0.5"
rand = "0.4.2"
serde_json = "1.0.1"
serde_test = "1.0.1"

[features]
default = ["native-tls"]
nightly-testing = ["rusoto_credential/nightly-testing"]
native-tls = ["hyper-tls"]
rustls = ["hyper-rustls"]
unstable = []
