[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
license = "MIT"
description = "AWS credential tooling"
documentation = "https://docs.rs/rusoto_credential"
name = "rusoto_credential"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.40.0"
exclude = ["tests/sample-data/*"]
edition = "2018"

[badges]
appveyor = { repository = "rusoto/rusoto", branch = "master" }
azure-devops = { project = "matthewkmayer/Rusoto", pipeline = "rusoto.rusoto", build="1" }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dirs = "1.0"
futures-preview = { version = "0.3.0-alpha.18", features = ["async-await", "nightly"] }
hyper = "0.13.0-alpha.1"
pin-project = "0.4.0-alpha.11"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "0.1"
tokio = "0.2.0-alpha.4"
tokio-net = { version = "0.2.0-alpha.4", features = ["process"] }

[dev-dependencies]
lazy_static = "1.0"
quickcheck = "0.6"

[dependencies.clippy]
optional = true
version = "0.0"

[features]
nightly-testing = []
unstable = []
